
workflows:
  build-unity-android:
    name: Build Unity Android APK
    max_build_duration: 60
    environment:
      vars:
        UNITY_VERSION: 2020.3.48f1
    scripts:
      - name: Set up Unity
        script: |
          echo "Using Unity version: $UNITY_VERSION"
      - name: Build Android APK
        script: |
          Unity -batchmode -nographics -silent-crashes \
          -projectPath . \
          -executeMethod BuildScript.BuildAndroid \
          -quit
    artifacts:
      - Builds/Android/*.apk
