workflows:
  unity-android-build:
    environment:
      vars:
        UNITY_VERSION: 2021.3.16f1
    scripts:
      - name: Build Android APK
        script: |
          /opt/unity/Editor/Unity \
          -batchmode \
          -nographics \
          -silent-crashes \
          -projectPath $CM_BUILD_DIR \
          -executeMethod BuildScript.BuildAndroid \
          -quit
    artifacts:
      - Builds/Android/*.apk
